pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    tools {
        maven "maven"
    }
    stages {
        stage('Build') {
            steps {
                echo "Executing for branch $BRANCH_NAME"
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            when {
                expression {
                    BRANCH_NAME = "master"
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
